apiVersion: v1
kind: Template
metadata:
  name: cassandra
  annotations:
    description: Cassandra cqlsh deploy
    tags: cassandra

parameters:
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: cassandra

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cassandra-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: app3-pv  

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: ${OBJECT_NAME_PREFIX}
          
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-claim     
      spec:
        containers:
        - name: cassandra-cql
          image: ${OBJECT_NAME_PREFIX}
          command:
          - "/opt/apache-cassandra/bin/docker-entrypoint.sh"
          - "--cluster_name=openstack-cluster"
          ports:
          - name: cql-port
            containerPort: 9042
          - name: thift-port
            containerPort: 9160
          - name:  intra-node
            containerPort: 7000
          - name: tls-intra
            containerPort: 7001    
        volumeMounts:
          - name: cassandra-data
            mountPath: "/var/lib/cassandra/data"
             
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - cassandra-cql
        from:
          kind: ImageStream
          name: ${OBJECT_NAME_PREFIX}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: cassandra-peers
    name: cassandra-peers
  spec:
    clusterIP: None
    ports:
      - port: 7000
        name: intra-node
      - port: 7001
        name: tls-intra
    selector:
      app: ${OBJECT_NAME_PREFIX}      
- apiVersion: v1
  kind: Service
  metadata:
    name: cassandra-cql
  spec:
    type: LoadBalancer
    ports:
    - port: 9042
      name: cql-port
      nodePort: 9042
    selector:
      app: ${OBJECT_NAME_PREFIX}      