apiVersion: v1
kind: Template
metadata:
  name: openstack-cassandra-build
  annotations:
    description: Cassandra builder for openstack-poc
    tags: logs,poc,openstack,cassandra

parameters:
- name: SOURCE_REPOSITORY_URL
  description: URL of the Git repository Dockerfile
  required: true
  value: https://github.com/vikasroonwal/openshift-cassandra.git
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: cassandra-openstack-poc

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${OBJECT_NAME_PREFIX}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    strategy:
      type: Docker
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}  
    output:
      to:
        kind: ImageStream
        name: ${OBJECT_NAME_PREFIX}
    triggers:
    - type: ConfigChange
